
services:
  api:
    # image: invoicedock-api:latest
    build: ./Backend
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=InvoiceDB;User Id=sa;Password=Password@123;TrustServerCertificate=True;
    depends_on:
       - db
    
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_invoicedb
    platform: linux/amd64
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password@123"
    ports:
      - "1434:1433"

  # migrate:
  #   profiles: ["ci-cd"]  # Add this line
  #   image: invoicedock-api:latest
  #   depends_on:
  #     - db
  #   environment:
  #     ASPNETCORE_ENVIRONMENT: "Development"
  #     ConnectionStrings__DefaultConnection: "Server=localhost,1434;Database=InvoiceDB;User Id=sa;Password=Password@123;TrustServerCertificate=True"
  #   entrypoint: ["dotnet", "API.dll", "--migrate"]
  #   restart: "no"

  client:
    # image: invoicedock-frontend:latest 
    build: ./Frontend
    ports:
      - "4200:80"
    depends_on:
      - api
      # - migrate
